apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pfa
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://github.com/mo-hamedaziz/pfa-infra.git
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
