apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: europe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: mohamedaziz0801/simple-flask-login:v1
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "run.py"
        - name: FLASK_ENV
          value: "development"
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres.shared-db.svc.cluster.local:5432/flask_db"
        - name: SECRET_KEY
          value: "supersecretkey"
        # envFrom:
        # - secretRef:
        #     name: web-secrets
        # # Remove the volume mount since the app is already in /app in the image

---

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: europe
spec:
  type: NodePort  # Changed from LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: web

# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: web-secrets
#   namespace: europe
# type: Opaque
# stringData:
#   .env: |
#     SECRET_KEY=supersecretkey
#     DATABASE_URL=postgresql://postgres:postgres@postgres.shared-db.svc.cluster.local:5432/flask_db