apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default

  # This directory now contains our Namespace + kustomization + values
  source:
    repoURL: https://github.com/mo-hamedaziz/pfa-infra.git
    targetRevision: main
    path: cluster-resources/vault

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
