apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:latest
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: config
              mountPath: /vault/config
              readOnly: true
            - name: data
              mountPath: /vault/data
          env:
            - name: VAULT_ADDR
              value: "http://0.0.0.0:8200"
            - name: VAULT_API_ADDR
              value: "http://0.0.0.0:8200"
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: vault-config
        - name: data
          emptyDir: {}