apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  valuesFrom:
  - kind: ConfigMap
    name: vault-config
  values:
    server:
      extraArgs: -config=/vault/config/vault-config.json
      extraEnvironmentVars:
        VAULT_ADDR: http://127.0.0.1:8200
      ha:
        enabled: true
        raft:
          enabled: true
          setNodeId: true
      volumes:
        - name: config
          configMap:
            name: vault-config
      volumeMounts:
        - mountPath: /vault/config
          name: config