server:
  ha:
    enabled: true
    replicas: 1
  dataStorage:
    enabled: true
    size: 1Gi
  auditStorage:
    enabled: false
  standalone:
    enabled: false
  dev:
    enabled: false
  extraEnvironmentVars:
    VAULT_LOCAL_CONFIG: |
      {
        "ui": true,
        "listener": [{
          "tcp": {
            "address": "0.0.0.0:8200",
            "tls_disable": 1
          }
        }],
        "storage": {
          "raft": {
            "path": "/vault/data"
          }
        },
        "default_lease_ttl": "168h",
        "max_lease_ttl": "720h",
        "api_addr": "http://vault.vault.svc:8200",
        "cluster_addr": "http://vault.vault.svc:8201"
      }
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false

injector:
  enabled: true

ui:
  enabled: true
