apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      version: 0.27.0  # Use the latest stable version
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    server:
      dev:
        enabled: true  # For development only - disable in production
      ha:
        enabled: false  # Disable HA for minikube
    injector:
      enabled: false   # Disable agent injector for simplicity