apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.27.0
    chart: vault
    helm:
      values: |
        server:
          ha:
            enabled: true
            replicas: 3
            config: |
              {
                "ui": true,
                "listener": [{
                  "tcp": {
                    "address": "0.0.0.0:8200",
                    "tls_disable": true
                  }
                }],
                "storage": {
                  "raft": {
                    "path": "/vault/data"
                  }
                },
                "cluster_addr": "http://POD_IP:8201",
                "api_addr": "http://POD_IP:8200"
              }
  syncPolicy:
    automated:
      prune: true
      selfHeal: true