server:
  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: standard
  ha:
    enabled: false
  standalone:
    enabled: true
    config: |
      ui = true
      storage "file" {
        path = "/vault/data"
      }
      listener "tcp" {
        address = "0.0.0.0:8200"
        tls_disable = 1
      }
      disable_mlock = true
  ingress:
    enabled: false
