apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault
spec:
  template:
    spec:
      serviceAccountName: default
      containers:
        - name: vault-init
          image: hashicorp/vault:1.14.0
          command:
            - /bin/sh
            - -c
            - |
              VAULT_ADDR='http://vault.vault.svc:8200'
              echo "Checking Vault status..."
              vault status || true
              if vault status | grep -q 'Initialized.*false'; then
                echo "Vault not initialized, initializing..."
                vault operator init -key-shares=1 -key-threshold=1 -format=json > /tmp/keys.json
                vault operator unseal $(jq -r .unseal_keys_b64[0] /tmp/keys.json)
                jq -r . > /vault/keys/keys.json < /tmp/keys.json
              else
                echo "Vault already initialized."
              fi
          volumeMounts:
            - name: vault-keys
              mountPath: /vault/keys
      restartPolicy: OnFailure
      volumes:
        - name: vault-keys
          emptyDir: {}
