apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-unsealer
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-unsealer
  namespace: vault
rules:
  # allow reading the SA token secret
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["vault-unsealer-token"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-unsealer
  namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-unsealer
subjects:
  - kind: ServiceAccount
    name: vault-unsealer
    namespace: vault
