apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
spec:
  type: NodePort
  selector:
    app: vault
  ports:
    - port: 8200
      targetPort: 8200
      # choose an open NodePort in minikube
      nodePort: 30000
