apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: NodePort
  selector:
    app: vault
  ports:
    - port: 8200
      targetPort: 8200
      # choose an open NodePort in minikube
      nodePort: 30000
