global:
  enabled: true

server:
  ha:
    enabled: true
    raft:
      enabled: true
      setNodeId: true
  dataStorage:
    size: 10Gi
  extraEnvironmentVars:
    VAULT_API_ADDR: "http://localhost:8200"
    VAULT_CLUSTER_ADDR: "http://localhost:8201"

  extraVolumes:
    - name: vault-init
      configMap:
        name: vault-init-script
  extraVolumeMounts:
    - name: vault-init
      mountPath: /vault/userconfig
      readOnly: true

  postStart:
    command:
      - "/bin/sh"
      - "-c"
      - "/vault/userconfig/init.sh || true"

  # Disable TLS for dev
  extraConfig: |
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }

    storage "raft" {
      path = "/vault/data"
      node_id = "vault-0"
    }

    ui = true
