# Basic values for a single-node Vault (adjust for HA if you need it)
server:
  # DEV-only: static root token (remove for prod!)
  extraArgs:
    - "-dev-root-token-id=root"
  ha:
    enabled: false

# Store data on a PersistentVolume
dataStorage:
  enabled: true
  size: 1Gi
