server:
  dev:
    enabled: true
  ha:
    enabled: false

  dataStorage:
    enabled: true
    size: 1Gi

  extraEnvironmentVars:
    VAULT_DEV_ROOT_TOKEN_ID: "root-token"

  service:
    type: ClusterIP

  ingress:
    enabled: false

  resources:
    requests:
      memory: 512Mi
      cpu: 250m

  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false

injector:
  enabled: false
