apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault-config.json: |
    {
      "ui": true,
      "disable_mlock": true,
      "listener": {
        "tcp": {
          "tls_disable": 1,
          "address": "[::]:8200",
          "cluster_address": "[::]:8201"
        }
      },
      "storage": {
        "raft": {
          "path": "/vault/data"
        }
      },
      "service_registration": {
        "kubernetes": {}
      }
    }