server:
  extraArgs: ["-dev"]
  dev:
    enabled: true
  dataStorage:
    enabled: false
  ha:
    enabled: false
  affinity: {}
  tolerations: []
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
