apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: vault-init
          image: curlimages/curl:8.5.0
          command:
            - /bin/sh
            - -c
            - |
              set -e

              VAULT_ADDR="http://vault.vault.svc.cluster.local:8200"

              echo "Waiting for Vault to become reachable..."
              until curl -s $VAULT_ADDR/v1/sys/health | grep -q '"initialized":'; do
                echo "Vault not reachable yet..."
                sleep 5
              done

              echo "Checking if Vault is already initialized..."
              if curl -s $VAULT_ADDR/v1/sys/init | grep -q '"initialized":true'; then
                echo "Vault is already initialized."
                exit 0
              fi

              echo "Initializing Vault..."
              curl -s --request PUT --data '{"secret_shares":1,"secret_threshold":1}' $VAULT_ADDR/v1/sys/init > /tmp/keys.json

              UNSEAL_KEY=$(jq -r .keys_base64[0] /tmp/keys.json)
              ROOT_TOKEN=$(jq -r .root_token /tmp/keys.json)

              echo "Unsealing Vault..."
              curl -s --request PUT --data '{"key":"'"$UNSEAL_KEY"'"}' $VAULT_ADDR/v1/sys/unseal

              echo "Storing credentials in Kubernetes secret..."
              kubectl create secret generic vault-init-keys \
                --from-literal=unseal_key="$UNSEAL_KEY" \
                --from-literal=root_token="$ROOT_TOKEN" \
                -n vault
