apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-configmap
  namespace: argocd
data:
  resource.customizations: |
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle