apiVersion: batch/v1
kind: Job
metadata:
  name: vault-secrets-setup
  namespace: vault
spec:
  template:
    spec:
      containers:
        - name: vault-setup
          image: vault:latest
          command:
            - /bin/sh
            - -c
            - |
              vault operator init
              vault operator unseal <UNSEAL_KEY_1>
              vault operator unseal <UNSEAL_KEY_2>
              vault operator unseal <UNSEAL_KEY_3>
              vault login <ROOT_TOKEN>
              vault secrets enable -path=secret kv-v2
      restartPolicy: OnFailure
