apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault
spec:
  template:
    spec:
      serviceAccountName: default
      containers:
        - name: vault-init
          image: hashicorp/vault:1.15.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              export VAULT_ADDR=http://vault.vault.svc.cluster.local:8200

              if vault status | grep -q 'Initialized.*true'; then
                echo "Vault already initialized"
              else
                vault operator init -key-shares=1 -key-threshold=1 -format=json > /tmp/vault-keys.json

                cat /tmp/vault-keys.json

                jq -r '.unseal_keys_b64[0]' /tmp/vault-keys.json | vault operator unseal -

                kubectl create secret generic vault-init-keys \
                  --from-file=vault-keys.json=/tmp/vault-keys.json \
                  -n vault
              fi
          env:
            - name: VAULT_SKIP_VERIFY
              value: "true"
      restartPolicy: OnFailure
