apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault
spec:
  template:
    spec:
      containers:
      - name: vault-init
        image: hashicorp/vault:latest
        command:
        - "sh"
        - "-c"
        - |
          # Initialize Vault and store the unseal keys and root token in a JSON file
          VAULT_ADDR="http://vault.vault.svc.cluster.local:8200"
          echo "Initializing Vault..."
          INIT_RESULT=$(curl --request POST --data '{"secret_shares": 5, "secret_threshold": 3}' $VAULT_ADDR/v1/sys/init)
          
          # Extract unseal keys and root token
          UNSEAL_KEYS=$(echo $INIT_RESULT | jq -r '.keys[]')
          ROOT_TOKEN=$(echo $INIT_RESULT | jq -r '.root_token')
          
          # Create JSON output
          OUTPUT_JSON=$(jq -n \
            --argjson unseal_keys "$(echo $UNSEAL_KEYS | jq -R . | jq -s .)" \
            --arg root_token "$ROOT_TOKEN" \
            '{unseal_keys: $unseal_keys, root_token: $root_token}')
          
          # Store the JSON file in the desired directory
          echo $OUTPUT_JSON > /vault/init-output.json
          
          # Copy the file to the host path /home/pfa/pfa-infra/cluster-resources/vault
          kubectl cp vault/vault-init:/vault/init-output.json /home/pfa/pfa-infra/cluster-resources/vault/init-output.json

      restartPolicy: Never
  backoffLimit: 4
