apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-init-script
  namespace: vault
data:
  init.sh: |
    #!/bin/sh
    set -e

    STATUS=$(vault status -format=json || true)

    if echo "$STATUS" | grep -q '"initialized": false'; then
      echo "Initializing Vault..."
      vault operator init -format=json > /vault/userconfig/init-keys.json

      UNSEAL_KEY=$(jq -r ".unseal_keys_b64[0]" /vault/userconfig/init-keys.json)
      vault operator unseal $UNSEAL_KEY
    elif echo "$STATUS" | grep -q '"sealed": true'; then
      echo "Unsealing Vault..."
      UNSEAL_KEY=$(jq -r ".unseal_keys_b64[0]" /vault/userconfig/init-keys.json)
      vault operator unseal $UNSEAL_KEY
    else
      echo "Vault already initialized and unsealed."
    fi
