apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default

  # ← no "path:" or "directory:" here!
  source:
    repoURL: https://github.com/mo-hamedaziz/pfa-infra.git
    targetRevision: HEAD
    helm:
      chart: vault
      repoURL: https://helm.releases.hashicorp.com
      valuesFile: values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
